In [11]:
import numpy as np

def keep_indices_as_nonzero(arr, indices):
    # indicesを整数型に変換 (浮動小数点を整数に)
    indices = np.asarray(indices).astype(int)
    
    # arrと同じ形状のゼロ配列を作成
    result = np.zeros_like(arr)
    
    # インデックスを使用して値をコピー
    result[:,indices] = arr[:,indices]
    
    
    return result

# 例
arr = np.array([[-9.35256508e-01, -1.14798096e+00, -1.57383065e+00,  1.58821305e+00,
                 4.04343644e+00,  3.78885890e+00],
                [ 3.16103711e+00, -3.04401356e+00,  4.73352891e+00,  1.79542443e+00,
                 -2.49976973e+00,  3.20240891e+00]])

indices = [0, 1]  # 例: 2Dインデックス (浮動小数点でもOK)
indices = np.array(indices)  # インデックスをNumPy配列に変換

# 結果を表示
result = keep_indices_as_nonzero(arr, indices)
print(result)


[[-0.93525651 -1.14798096  0.          0.          0.          0.        ]
 [ 3.16103711 -3.04401356  0.          0.          0.          0.        ]]


In [12]:
gnn_label = [[5],[4],[2],[3],[1],[0]]

In [24]:
print(gnn_label[0])

[5]


In [26]:
print(gnn_label[0])

[5]


In [23]:
gnn_label = np.array(gnn_label)

In [30]:
labels = [[5],[0],[4],[1],[6],[1]]
labels = np.array(labels)

In [31]:
labels[0]

array([5])

In [32]:
def keep_indices_as_nonzero(arr, indices):
    arr = arr
    indices = np.asarray(indices, dtype=int)
    # 元の配列と同じ形状でゼロ配列を作成
    result = np.zeros_like(arr)
    # 指定されたインデックスに対応する要素をコピー
    result[:,indices] = arr[:,indices]
    return result

In [34]:
arr =  [[1,2,3,4,5,6]]
arr = np.array(arr)
keep_indices_as_nonzero(arr,labels[0])

array([[0, 0, 0, 0, 0, 6]])

In [53]:
x = [  0.,    0.     ,       0. ,           0.   ,         0.,
     0.        ]
dim = 6

In [54]:
def rastrigin(x):
    A = 10
    x = np.asarray(x)  # 入力をNumPy配列に変換
    n = x.size         # 次元数
    term1 = A * n
    term2 = np.sum(x**2 - A * np.cos(2 * np.pi * x))
    return term1 + term2
def objective_function_ga(x,dim):
    n_rosenbrock = dim
   
    rosen_value = rastrigin(x)
    print(rosen_value)
    return rosen_value

In [55]:
objective_function_ga(x,dim)

0.0


np.float64(0.0)

In [1]:
import numpy as np
import torch
import torch.nn as nn

class CustomModel(nn.Module):
    def __init__(self):
        super(CustomModel, self).__init__()
        self.fc1 = nn.Linear(6, 10)
        self.fc2 = nn.Linear(10, 1)

    def forward(self, x, dim=None):
        # numpy配列をPyTorchテンソルに変換
        if isinstance(x, np.ndarray):
            x = torch.tensor(x, dtype=torch.float32)
        
        if dim is not None:
            # 特定次元のみを選択（推論用）
            x = x[:, dim].unsqueeze(1)  # dim次元を抽出し形状調整
        # 通常のモデル処理
        x = self.fc1(x)
        x = torch.relu(x)
        x = self.fc2(x)
        return x

# モデルの初期化
model = CustomModel()

# 学習時の6次元データ（numpy形式）
input_train = np.random.randn(32, 6).astype(np.float32)  # バッチサイズ32、次元6
output_train = model(input_train)  # dim=Noneで全次元使用

# 推論時の6次元データ（numpy形式）
input_test = np.random.randn(32, 6).astype(np.float32)  # バッチサイズ32、次元6
output_test = model(input_test, dim=2)  # dim=2で第2次元を選択


RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x1 and 6x10)

In [2]:
import numpy as np

In [3]:
array_int = np.zeros((100, 6), dtype=int)

In [5]:
array_int[:,5]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
one = np.ones((100,1),dtype=float)