In [1]:
import numpy as np

# 各列で最大値と2番目に大きい値のインデックス（例）
largest_indices = [2, 2, 4, 0, 0, 0]
second_largest_indices = [3, 1, 0, 4, 4, 4]

# ノード数（例では6入力ノード + 6出力ノード = 12）
num_nodes = 6 + 6  # 入力ノード6個、出力ノード6個
adjacency_matrix = np.zeros((num_nodes, num_nodes), dtype=int)

# 隣接行列を作成
for input_node in range(6):  # 入力ノードは0〜5
    output_node_1 = largest_indices[input_node] + 6  # 最大値のノード（+6で出力ノードに対応）
    output_node_2 = second_largest_indices[input_node] + 6  # 2番目のノード

    # 隣接行列にエッジを設定
    adjacency_matrix[input_node, output_node_1] = 1
    adjacency_matrix[input_node, output_node_2] = 1

# 隣接行列を表示
print("隣接行列:")
print(adjacency_matrix)


隣接行列:
[[0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]


In [2]:
import numpy as np

# 出力のインデックス
largest_indices = [2, 2, 4, 0, 0, 0]
second_largest_indices = [3, 1, 0, 4, 4, 4]

# ノード数 (ここでは6つのノード)
num_nodes = len(largest_indices)

# srcとdstを格納するリスト
src = []
dst = []

# 各ノードに対して接続先を追加
for node in range(num_nodes):
    # 最大値のインデックスと2番目に大きい値のインデックスを使って接続を作成
    src.append(node)
    dst.append(largest_indices[node] + num_nodes)  # ノード番号を6足して接続
    
    src.append(node)
    dst.append(second_largest_indices[node] + num_nodes)  # 同様に接続
    
# 結果を表示
print("src:", src)
print("dst:", dst)


src: [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5]
dst: [8, 9, 8, 7, 10, 6, 6, 10, 6, 10, 6, 10]


In [3]:
import numpy as np

# 出力のインデックス（np.int64型も問題なく処理可能）
largest_indices = [np.int64(1), np.int64(1), np.int64(1), np.int64(0), np.int64(0)]
second_largest_indices = [np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(1)]

# ノード数 (ここでは5つのノード)
num_nodes = len(largest_indices)

# srcとdstを格納するリスト
src = []
dst = []

# 各ノードに対して接続先を追加
for node in range(num_nodes):
    # 最大値のインデックスと2番目に大きい値のインデックスを使って接続を作成
    src.append(node)
    dst.append(largest_indices[node] + num_nodes)  # ノード番号を5足して接続
    
    src.append(node)
    dst.append(second_largest_indices[node] + num_nodes)  # 同様に接続
    
# 結果を表示
print("src:", src)
print("dst:", dst)


src: [0, 0, 1, 1, 2, 2, 3, 3, 4, 4]
dst: [np.int64(6), np.int64(5), np.int64(6), np.int64(5), np.int64(6), np.int64(5), np.int64(5), np.int64(6), np.int64(5), np.int64(6)]


In [4]:
import numpy as np

# 出力のインデックス（np.int64型が含まれている）
largest_indices = [np.int64(1), np.int64(1), np.int64(1), np.int64(0), np.int64(0)]
second_largest_indices = [np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(1)]

# np.int64型をint型に変換
largest_indices = [int(i) for i in largest_indices]
second_largest_indices = [int(i) for i in second_largest_indices]

# ノード数 (ここでは5つのノード)
num_nodes = len(largest_indices)

# srcとdstを格納するリスト
src = []
dst = []

# 各ノードに対して接続先を追加
for node in range(num_nodes):
    # 最大値のインデックスと2番目に大きい値のインデックスを使って接続を作成
    src.append(node)
    dst.append(largest_indices[node] + num_nodes)  # ノード番号を5足して接続
    
    src.append(node)
    dst.append(second_largest_indices[node] + num_nodes)  # 同様に接続
    
#


In [6]:
import numpy as np

# 出力のインデックス（np.int64型が含まれている）
largest_indices = [np.int64(1), np.int64(1), np.int64(1), np.int64(0), np.int64(0)]
second_largest_indices = [np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(1)]

# np.int64型をint型に変換
largest_indices = [int(i) for i in largest_indices]
second_largest_indices = [int(i) for i in second_largest_indices]

# ノード数 (ここでは5つのノード)
num_nodes = len(largest_indices)

# srcとdstを格納するリスト
src = []
dst = []

# 各ノードに対して接続先を追加
for node in range(num_nodes):
    # 最大値のインデックスと2番目に大きい値のインデックスを使って接続を作成
    src.append(node)
    dst.append(largest_indices[node] + num_nodes+1)  # ノード番号を5足して接続
    
    src.append(node)
    dst.append(second_largest_indices[node] + num_nodes+1)  # 同様に接続
    
# 結果を表示
print("src:", src)
print("dst:", dst)


src: [0, 0, 1, 1, 2, 2, 3, 3, 4, 4]
dst: [7, 6, 7, 6, 7, 6, 6, 7, 6, 7]


In [9]:
import numpy as np

# 既存のsrcとdst
src = [0, 0, 1, 1, 2, 2, 3, 3, 4, 4]
dst = [7, 6, 7, 6, 7, 6, 6, 7, 6, 7]

# 新しいlargest_indicesとsecond_largest_indices
largest_indices = [np.int64(4), np.int64(0), np.int64(3), np.int64(4), np.int64(0),
                   np.int64(1), np.int64(0), np.int64(3), np.int64(0), np.int64(2)]
second_largest_indices = [np.int64(0), np.int64(4), np.int64(1), np.int64(0), np.int64(4),
                          np.int64(2), np.int64(4), np.int64(1), np.int64(4), np.int64(3)]

# ノード数
num_nodes = len(largest_indices)

# 新しいsrcとdstを追加する
for node in range(num_nodes):
    # 最初の接続: 最大値のインデックス
    src.append(node + 5)  # ノード番号を5足して接続
    dst.append(largest_indices[node] + 9)  # 最大値に5を足して接続
    
    # 2番目の接続: 2番目に大きい値のインデックス
    src.append(node + 5)  # ノード番号を5足して接続
    dst.append(second_largest_indices[node] + 9)  # 2番目に大きい値に5を足して接続

# 結果の表示
print("src:", src)
print("dst:", dst)


src: [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14]
dst: [7, 6, 7, 6, 7, 6, 6, 7, 6, 7, np.int64(13), np.int64(9), np.int64(9), np.int64(13), np.int64(12), np.int64(10), np.int64(13), np.int64(9), np.int64(9), np.int64(13), np.int64(10), np.int64(11), np.int64(9), np.int64(13), np.int64(12), np.int64(10), np.int64(9), np.int64(13), np.int64(11), np.int64(12)]


In [ ]:
import numpy as np

# 既存のsrcとdst
src = [0, 0, 1, 1, 2, 2, 3, 3, 4, 4]
dst = [7, 6, 7, 6, 7, 6, 6, 7, 6, 7]

# 新しいlargest_indicesとsecond_largest_indices
largest_indices = [np.int64(4), np.int64(0), np.int64(3), np.int64(4), np.int64(0),
                   np.int64(1), np.int64(0), np.int64(3), np.int64(0), np.int64(2)]
second_largest_indices = [np.int64(0), np.int64(4), np.int64(1), np.int64(0), np.int64(4),
                          np.int64(2), np.int64(4), np.int64(1), np.int64(4), np.int64(3)]
# ここから src を変更: dstの各要素に対応するsrcを2回ずつ追加する
extended_src = []
extended_dst = []

for d in dst:
    extended_src.append(src[dst.index(d)])
    extended_src.append(src[dst.index(d)])  # 同じsrcを2回追加
    src.append(d)
    src.append(d)  # 同じdstを2回追加
        # 最初の接続: 最大値のインデックス
    # src.append(node + 5)  # ノード番号を5足して接続
    dst.append(largest_indices[d] + 9)  # 最大値に5を足して接続
    
    # 2番目の接続: 2番目に大きい値のインデックス
    # src.append(node + 5)  # ノード番号を5足して接続
    dst.append(second_largest_indices[d] + 5)  # 2番目に大きい値に5を足して接続
    extended_dst.append(largest_indices[d] + 9)
    extended_dst.append(second_largest_indices[d] + 9)
# 結果の表示
print("extended_src:", extended_src)
print("extended_dst:", extended_dst)
# ノード数
num_nodes = len(largest_indices)



print(src)
print(dst)



extended_src: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
extended_dst: []
[0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 7, 7, 6, 6, 7, 7, 6, 6, 7, 7, 6, 6, 6, 6, 7, 7, 6, 6, 7, 7]
[7, 6, 7, 6, 7, 6, 6, 7, 6, 7, np.int64(9), np.int64(5), np.int64(5), np.int64(9), np.int64(8), np.int64(6), np.int64(9), np.int64(5), np.int64(5), np.int64(9), np.int64(6), np.int64(7), np.int64(5), np.int64(9), np.int64(8), np.int64(6), np.int64(5), np.int64(9), np.int64(7), np.int64(8)]
